// Code generated by go-swagger; DO NOT EDIT.

package pages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetStatReader is a Reader for the GetStat structure.
type GetStatReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStatReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetStatOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /stat] GetStat", response, response.Code())
	}
}

// NewGetStatOK creates a GetStatOK with default headers values
func NewGetStatOK() *GetStatOK {
	return &GetStatOK{}
}

/*
GetStatOK describes a response with status code 200, with default header values.

TorrServer statistics
*/
type GetStatOK struct {
}

// IsSuccess returns true when this get stat o k response has a 2xx status code
func (o *GetStatOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get stat o k response has a 3xx status code
func (o *GetStatOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stat o k response has a 4xx status code
func (o *GetStatOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stat o k response has a 5xx status code
func (o *GetStatOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get stat o k response a status code equal to that given
func (o *GetStatOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get stat o k response
func (o *GetStatOK) Code() int {
	return 200
}

func (o *GetStatOK) Error() string {
	return fmt.Sprintf("[GET /stat][%d] getStatOK", 200)
}

func (o *GetStatOK) String() string {
	return fmt.Sprintf("[GET /stat][%d] getStatOK", 200)
}

func (o *GetStatOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
