// Code generated by go-swagger; DO NOT EDIT.

package pages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetMagnetsReader is a Reader for the GetMagnets structure.
type GetMagnetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMagnetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetMagnetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /magnets] GetMagnets", response, response.Code())
	}
}

// NewGetMagnetsOK creates a GetMagnetsOK with default headers values
func NewGetMagnetsOK() *GetMagnetsOK {
	return &GetMagnetsOK{}
}

/*
GetMagnetsOK describes a response with status code 200, with default header values.

HTML with Magnet links
*/
type GetMagnetsOK struct {
}

// IsSuccess returns true when this get magnets o k response has a 2xx status code
func (o *GetMagnetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get magnets o k response has a 3xx status code
func (o *GetMagnetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get magnets o k response has a 4xx status code
func (o *GetMagnetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get magnets o k response has a 5xx status code
func (o *GetMagnetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get magnets o k response a status code equal to that given
func (o *GetMagnetsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get magnets o k response
func (o *GetMagnetsOK) Code() int {
	return 200
}

func (o *GetMagnetsOK) Error() string {
	return fmt.Sprintf("[GET /magnets][%d] getMagnetsOK", 200)
}

func (o *GetMagnetsOK) String() string {
	return fmt.Sprintf("[GET /magnets][%d] getMagnetsOK", 200)
}

func (o *GetMagnetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
