// Code generated by go-swagger; DO NOT EDIT.

package pages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMagnetsParams creates a new GetMagnetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMagnetsParams() *GetMagnetsParams {
	return &GetMagnetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMagnetsParamsWithTimeout creates a new GetMagnetsParams object
// with the ability to set a timeout on a request.
func NewGetMagnetsParamsWithTimeout(timeout time.Duration) *GetMagnetsParams {
	return &GetMagnetsParams{
		timeout: timeout,
	}
}

// NewGetMagnetsParamsWithContext creates a new GetMagnetsParams object
// with the ability to set a context for a request.
func NewGetMagnetsParamsWithContext(ctx context.Context) *GetMagnetsParams {
	return &GetMagnetsParams{
		Context: ctx,
	}
}

// NewGetMagnetsParamsWithHTTPClient creates a new GetMagnetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMagnetsParamsWithHTTPClient(client *http.Client) *GetMagnetsParams {
	return &GetMagnetsParams{
		HTTPClient: client,
	}
}

/*
GetMagnetsParams contains all the parameters to send to the API endpoint

	for the get magnets operation.

	Typically these are written to a http.Request.
*/
type GetMagnetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get magnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMagnetsParams) WithDefaults() *GetMagnetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get magnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMagnetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get magnets params
func (o *GetMagnetsParams) WithTimeout(timeout time.Duration) *GetMagnetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get magnets params
func (o *GetMagnetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get magnets params
func (o *GetMagnetsParams) WithContext(ctx context.Context) *GetMagnetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get magnets params
func (o *GetMagnetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get magnets params
func (o *GetMagnetsParams) WithHTTPClient(client *http.Client) *GetMagnetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get magnets params
func (o *GetMagnetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMagnetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
