// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rtorrent.proto

package rtorrent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RacoonTorrent service

type RacoonTorrentService interface {
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type racoonTorrentService struct {
	c    client.Client
	name string
}

func NewRacoonTorrentService(name string, c client.Client) RacoonTorrentService {
	return &racoonTorrentService{
		c:    c,
		name: name,
	}
}

func (c *racoonTorrentService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "RacoonTorrent.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RacoonTorrent service

type RacoonTorrentHandler interface {
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterRacoonTorrentHandler(s server.Server, hdlr RacoonTorrentHandler, opts ...server.HandlerOption) error {
	type racoonTorrent interface {
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
	}
	type RacoonTorrent struct {
		racoonTorrent
	}
	h := &racoonTorrentHandler{hdlr}
	return s.Handle(s.NewHandler(&RacoonTorrent{h}, opts...))
}

type racoonTorrentHandler struct {
	RacoonTorrentHandler
}

func (h *racoonTorrentHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.RacoonTorrentHandler.Search(ctx, in, out)
}
