// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rtorrent.proto

package rtorrent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchResponse_ErrorCode int32

const (
	SearchResponse_OK               SearchResponse_ErrorCode = 0
	SearchResponse_CAPTCHA_REQUIRED SearchResponse_ErrorCode = 1
	SearchResponse_ERROR            SearchResponse_ErrorCode = 3
)

var SearchResponse_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "CAPTCHA_REQUIRED",
	3: "ERROR",
}

var SearchResponse_ErrorCode_value = map[string]int32{
	"OK":               0,
	"CAPTCHA_REQUIRED": 1,
	"ERROR":            3,
}

func (x SearchResponse_ErrorCode) String() string {
	return proto.EnumName(SearchResponse_ErrorCode_name, int32(x))
}

func (SearchResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{2, 0}
}

type SearchRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Captcha              string   `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Tracker              string   `protobuf:"bytes,5,opt,name=tracker,proto3" json:"tracker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SearchRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SearchRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *SearchRequest) GetTracker() string {
	if m != nil {
		return m.Tracker
	}
	return ""
}

type Torrent struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Size                 string   `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Quality              string   `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Torrent) Reset()         { *m = Torrent{} }
func (m *Torrent) String() string { return proto.CompactTextString(m) }
func (*Torrent) ProtoMessage()    {}
func (*Torrent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{1}
}

func (m *Torrent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Torrent.Unmarshal(m, b)
}
func (m *Torrent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Torrent.Marshal(b, m, deterministic)
}
func (m *Torrent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Torrent.Merge(m, src)
}
func (m *Torrent) XXX_Size() int {
	return xxx_messageInfo_Torrent.Size(m)
}
func (m *Torrent) XXX_DiscardUnknown() {
	xxx_messageInfo_Torrent.DiscardUnknown(m)
}

var xxx_messageInfo_Torrent proto.InternalMessageInfo

func (m *Torrent) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Torrent) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Torrent) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Torrent) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

type SearchResponse struct {
	SessionID            string                   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Code                 SearchResponse_ErrorCode `protobuf:"varint,2,opt,name=code,proto3,enum=SearchResponse_ErrorCode" json:"code,omitempty"`
	ErrorReason          string                   `protobuf:"bytes,3,opt,name=errorReason,proto3" json:"errorReason,omitempty"`
	CaptchaURL           string                   `protobuf:"bytes,4,opt,name=captchaURL,proto3" json:"captchaURL,omitempty"`
	Results              []*Torrent               `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *SearchResponse) GetCode() SearchResponse_ErrorCode {
	if m != nil {
		return m.Code
	}
	return SearchResponse_OK
}

func (m *SearchResponse) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

func (m *SearchResponse) GetCaptchaURL() string {
	if m != nil {
		return m.CaptchaURL
	}
	return ""
}

func (m *SearchResponse) GetResults() []*Torrent {
	if m != nil {
		return m.Results
	}
	return nil
}

type DownloadRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	TorrentLink          string   `protobuf:"bytes,2,opt,name=torrentLink,proto3" json:"torrentLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{3}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *DownloadRequest) GetTorrentLink() string {
	if m != nil {
		return m.TorrentLink
	}
	return ""
}

type DownloadResponse struct {
	DownloadStarted      bool     `protobuf:"varint,1,opt,name=downloadStarted,proto3" json:"downloadStarted,omitempty"`
	ErrorReason          string   `protobuf:"bytes,2,opt,name=errorReason,proto3" json:"errorReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{4}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetDownloadStarted() bool {
	if m != nil {
		return m.DownloadStarted
	}
	return false
}

func (m *DownloadResponse) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

type ListTrackersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTrackersRequest) Reset()         { *m = ListTrackersRequest{} }
func (m *ListTrackersRequest) String() string { return proto.CompactTextString(m) }
func (*ListTrackersRequest) ProtoMessage()    {}
func (*ListTrackersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{5}
}

func (m *ListTrackersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTrackersRequest.Unmarshal(m, b)
}
func (m *ListTrackersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTrackersRequest.Marshal(b, m, deterministic)
}
func (m *ListTrackersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTrackersRequest.Merge(m, src)
}
func (m *ListTrackersRequest) XXX_Size() int {
	return xxx_messageInfo_ListTrackersRequest.Size(m)
}
func (m *ListTrackersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTrackersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTrackersRequest proto.InternalMessageInfo

type TrackerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LoginRequired        bool     `protobuf:"varint,3,opt,name=loginRequired,proto3" json:"loginRequired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackerInfo) Reset()         { *m = TrackerInfo{} }
func (m *TrackerInfo) String() string { return proto.CompactTextString(m) }
func (*TrackerInfo) ProtoMessage()    {}
func (*TrackerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{6}
}

func (m *TrackerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackerInfo.Unmarshal(m, b)
}
func (m *TrackerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackerInfo.Marshal(b, m, deterministic)
}
func (m *TrackerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackerInfo.Merge(m, src)
}
func (m *TrackerInfo) XXX_Size() int {
	return xxx_messageInfo_TrackerInfo.Size(m)
}
func (m *TrackerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TrackerInfo proto.InternalMessageInfo

func (m *TrackerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TrackerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrackerInfo) GetLoginRequired() bool {
	if m != nil {
		return m.LoginRequired
	}
	return false
}

type ListTrackersResponse struct {
	Trackers             []*TrackerInfo `protobuf:"bytes,1,rep,name=trackers,proto3" json:"trackers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListTrackersResponse) Reset()         { *m = ListTrackersResponse{} }
func (m *ListTrackersResponse) String() string { return proto.CompactTextString(m) }
func (*ListTrackersResponse) ProtoMessage()    {}
func (*ListTrackersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a572d4ed2562a8b, []int{7}
}

func (m *ListTrackersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTrackersResponse.Unmarshal(m, b)
}
func (m *ListTrackersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTrackersResponse.Marshal(b, m, deterministic)
}
func (m *ListTrackersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTrackersResponse.Merge(m, src)
}
func (m *ListTrackersResponse) XXX_Size() int {
	return xxx_messageInfo_ListTrackersResponse.Size(m)
}
func (m *ListTrackersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTrackersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTrackersResponse proto.InternalMessageInfo

func (m *ListTrackersResponse) GetTrackers() []*TrackerInfo {
	if m != nil {
		return m.Trackers
	}
	return nil
}

func init() {
	proto.RegisterEnum("SearchResponse_ErrorCode", SearchResponse_ErrorCode_name, SearchResponse_ErrorCode_value)
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*Torrent)(nil), "Torrent")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*DownloadRequest)(nil), "DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "DownloadResponse")
	proto.RegisterType((*ListTrackersRequest)(nil), "ListTrackersRequest")
	proto.RegisterType((*TrackerInfo)(nil), "TrackerInfo")
	proto.RegisterType((*ListTrackersResponse)(nil), "ListTrackersResponse")
}

func init() { proto.RegisterFile("rtorrent.proto", fileDescriptor_7a572d4ed2562a8b) }

var fileDescriptor_7a572d4ed2562a8b = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0xfd, 0x6d, 0xfe, 0x6e, 0x26, 0x4d, 0xb2, 0x3f, 0x93, 0x4a, 0x4b, 0x84, 0x50, 0x64, 0x71,
	0x08, 0x07, 0x8c, 0x14, 0xb8, 0x71, 0xa1, 0x4a, 0x22, 0x11, 0x11, 0xa9, 0xd4, 0x4d, 0xc5, 0x0d,
	0x64, 0x76, 0x0d, 0xb5, 0xba, 0xd8, 0xa9, 0xed, 0xa8, 0xc0, 0x37, 0xe0, 0x9b, 0xf0, 0x15, 0xb9,
	0xa1, 0x75, 0xec, 0xfc, 0xa3, 0xe2, 0x36, 0xf3, 0x66, 0x77, 0xde, 0x9b, 0x99, 0xb7, 0x0b, 0x5d,
	0x6d, 0x95, 0xd6, 0x5c, 0x5a, 0xb2, 0xd2, 0xca, 0x2a, 0xfc, 0x33, 0x82, 0xce, 0x25, 0x67, 0x3a,
	0xbb, 0xa6, 0xfc, 0x76, 0xcd, 0x8d, 0x45, 0x7d, 0xa8, 0x17, 0xea, 0x8b, 0x90, 0x69, 0x34, 0x8c,
	0x46, 0x2d, 0xba, 0x49, 0xd0, 0x00, 0xe2, 0x15, 0x33, 0xe6, 0x4e, 0xe9, 0x3c, 0xad, 0xb8, 0xc2,
	0x36, 0x47, 0x08, 0x6a, 0x96, 0x7f, 0xb3, 0x69, 0xd5, 0xe1, 0x2e, 0x46, 0x29, 0x34, 0x33, 0xb6,
	0xb2, 0xd9, 0x35, 0x4b, 0x6b, 0x0e, 0x0e, 0x69, 0x59, 0xb1, 0x9a, 0x65, 0x37, 0x5c, 0xa7, 0xf5,
	0x4d, 0xc5, 0xa7, 0x98, 0x41, 0x73, 0xb9, 0x11, 0x57, 0x8a, 0xb0, 0xc2, 0x16, 0x3c, 0x88, 0x70,
	0x49, 0x49, 0x54, 0x08, 0x79, 0xe3, 0x05, 0xb8, 0xb8, 0xc4, 0x8c, 0xf8, 0xc1, 0x03, 0x79, 0x19,
	0x97, 0x14, 0xb7, 0x6b, 0x56, 0x08, 0xfb, 0x3d, 0x90, 0xfb, 0x14, 0xff, 0x8e, 0xa0, 0x1b, 0xc6,
	0x35, 0x2b, 0x25, 0x0d, 0x47, 0x8f, 0xa0, 0x65, 0xb8, 0x31, 0x42, 0xc9, 0xf9, 0xd4, 0xd3, 0xed,
	0x00, 0xf4, 0x0c, 0x6a, 0x99, 0xca, 0xb9, 0xa3, 0xec, 0x8e, 0x1f, 0x92, 0xc3, 0x97, 0xc9, 0x4c,
	0x6b, 0xa5, 0x27, 0x2a, 0xe7, 0xd4, 0x3d, 0x86, 0x86, 0xd0, 0xe6, 0x25, 0x44, 0x39, 0x33, 0x4a,
	0x7a, 0x51, 0xfb, 0x10, 0x7a, 0x0c, 0xe0, 0x37, 0x71, 0x45, 0x17, 0x5e, 0xde, 0x1e, 0x82, 0x30,
	0x34, 0x35, 0x37, 0xeb, 0xc2, 0x9a, 0xb4, 0x3e, 0xac, 0x8e, 0xda, 0xe3, 0x98, 0xf8, 0xa5, 0xd0,
	0x50, 0xc0, 0x2f, 0xa1, 0xb5, 0x25, 0x46, 0x0d, 0xa8, 0x9c, 0xbf, 0x4d, 0xfe, 0x43, 0x7d, 0x48,
	0x26, 0x67, 0xef, 0x96, 0x93, 0x37, 0x67, 0x1f, 0xe9, 0xec, 0xe2, 0x6a, 0x4e, 0x67, 0xd3, 0x24,
	0x42, 0x2d, 0xa8, 0xcf, 0x28, 0x3d, 0xa7, 0x49, 0x15, 0x5f, 0x40, 0x6f, 0xaa, 0xee, 0x64, 0xa1,
	0x58, 0x1e, 0x6e, 0xfd, 0xef, 0xd9, 0x87, 0xd0, 0xf6, 0x66, 0x59, 0xec, 0xb6, 0xbe, 0x0f, 0xe1,
	0x0f, 0x90, 0xec, 0x5a, 0xfa, 0x7d, 0x8e, 0xa0, 0x97, 0x7b, 0xec, 0xd2, 0x32, 0x6d, 0x79, 0xee,
	0x3a, 0xc7, 0xf4, 0x18, 0x3e, 0x5e, 0x56, 0xe5, 0xaf, 0x65, 0xe1, 0x53, 0x78, 0xb0, 0x10, 0xc6,
	0x2e, 0x37, 0x06, 0x31, 0x5e, 0x36, 0x7e, 0x0f, 0x6d, 0x0f, 0xcd, 0xe5, 0x67, 0x85, 0xba, 0x50,
	0x11, 0xb9, 0x97, 0x5f, 0x11, 0xce, 0x8f, 0x92, 0x7d, 0xe5, 0xc1, 0x26, 0x65, 0x8c, 0x9e, 0x40,
	0xc7, 0x19, 0xb9, 0x6c, 0x21, 0x34, 0xcf, 0xdd, 0x69, 0x62, 0x7a, 0x08, 0xe2, 0xd7, 0xd0, 0x3f,
	0xe4, 0xdb, 0xce, 0x14, 0x7b, 0x93, 0x9a, 0x34, 0x72, 0x57, 0x39, 0x21, 0x7b, 0x0a, 0xe8, 0xb6,
	0x3a, 0xfe, 0x15, 0x41, 0x87, 0xb2, 0x4c, 0x29, 0x19, 0xac, 0xfc, 0x0a, 0x4e, 0xf6, 0x7b, 0xa2,
	0x3e, 0xb9, 0x67, 0xa4, 0xc1, 0x29, 0xb9, 0x97, 0xf8, 0x29, 0x34, 0x36, 0x8e, 0x43, 0x5d, 0x72,
	0xf0, 0x99, 0x0e, 0x7a, 0x47, 0x56, 0x44, 0xcf, 0x21, 0x0e, 0xb7, 0x40, 0x09, 0x39, 0xba, 0xf4,
	0xe0, 0x7f, 0x72, 0x7c, 0xa8, 0x4f, 0x0d, 0xf7, 0x07, 0x78, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0x76, 0x7d, 0x59, 0x13, 0x04, 0x00, 0x00,
}
