// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APITorrReqJS api torr req j s
//
// swagger:model api.torrReqJS
type APITorrReqJS struct {

	// action
	Action string `json:"action,omitempty"`

	// category
	Category string `json:"category,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// poster
	Poster string `json:"poster,omitempty"`

	// save to db
	SaveToDb bool `json:"save_to_db,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this api torr req j s
func (m *APITorrReqJS) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api torr req j s based on context it is used
func (m *APITorrReqJS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APITorrReqJS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APITorrReqJS) UnmarshalBinary(b []byte) error {
	var res APITorrReqJS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
