// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APISetsReqJS api sets req j s
//
// swagger:model api.setsReqJS
type APISetsReqJS struct {

	// action
	Action string `json:"action,omitempty"`

	// sets
	Sets *SettingsBTSets `json:"sets,omitempty"`
}

// Validate validates this api sets req j s
func (m *APISetsReqJS) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APISetsReqJS) validateSets(formats strfmt.Registry) error {
	if swag.IsZero(m.Sets) { // not required
		return nil
	}

	if m.Sets != nil {
		if err := m.Sets.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sets")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this api sets req j s based on the context it is used
func (m *APISetsReqJS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APISetsReqJS) contextValidateSets(ctx context.Context, formats strfmt.Registry) error {

	if m.Sets != nil {

		if swag.IsZero(m.Sets) { // not required
			return nil
		}

		if err := m.Sets.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sets")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APISetsReqJS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISetsReqJS) UnmarshalBinary(b []byte) error {
	var res APISetsReqJS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
