// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIViewedReqJS api viewed req j s
//
// swagger:model api.viewedReqJS
type APIViewedReqJS struct {

	// action
	Action string `json:"action,omitempty"`

	// file index
	FileIndex int64 `json:"file_index,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`
}

// Validate validates this api viewed req j s
func (m *APIViewedReqJS) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api viewed req j s based on context it is used
func (m *APIViewedReqJS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIViewedReqJS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIViewedReqJS) UnmarshalBinary(b []byte) error {
	var res APIViewedReqJS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
