// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsTorrentDetails models torrent details
//
// swagger:model models.TorrentDetails
type ModelsTorrentDetails struct {

	// audio quality
	AudioQuality int64 `json:"audioQuality,omitempty"`

	// categories
	Categories string `json:"categories,omitempty"`

	// create date
	CreateDate string `json:"createDate,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// imdbid
	Imdbid string `json:"imdbid,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// magnet
	Magnet string `json:"magnet,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// names
	Names []string `json:"names"`

	// peer
	Peer int64 `json:"peer,omitempty"`

	// seed
	Seed int64 `json:"seed,omitempty"`

	// size
	Size string `json:"size,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// tracker
	Tracker string `json:"tracker,omitempty"`

	// video quality
	VideoQuality int64 `json:"videoQuality,omitempty"`

	// year
	Year int64 `json:"year,omitempty"`
}

// Validate validates this models torrent details
func (m *ModelsTorrentDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models torrent details based on context it is used
func (m *ModelsTorrentDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsTorrentDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsTorrentDetails) UnmarshalBinary(b []byte) error {
	var res ModelsTorrentDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
