// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SettingsViewed settings viewed
//
// swagger:model settings.Viewed
type SettingsViewed struct {

	// file index
	FileIndex int64 `json:"file_index,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`
}

// Validate validates this settings viewed
func (m *SettingsViewed) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this settings viewed based on context it is used
func (m *SettingsViewed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SettingsViewed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SettingsViewed) UnmarshalBinary(b []byte) error {
	var res SettingsViewed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
