// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SettingsTorznabConfig settings torznab config
//
// swagger:model settings.TorznabConfig
type SettingsTorznabConfig struct {

	// host
	Host string `json:"host,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this settings torznab config
func (m *SettingsTorznabConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this settings torznab config based on context it is used
func (m *SettingsTorznabConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SettingsTorznabConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SettingsTorznabConfig) UnmarshalBinary(b []byte) error {
	var res SettingsTorznabConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
