// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StateItemState state item state
//
// swagger:model state.ItemState
type StateItemState struct {

	// completed
	Completed bool `json:"completed,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// length
	Length int64 `json:"length,omitempty"`

	// priority
	Priority int64 `json:"priority,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

// Validate validates this state item state
func (m *StateItemState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this state item state based on context it is used
func (m *StateItemState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StateItemState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateItemState) UnmarshalBinary(b []byte) error {
	var res StateItemState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
