// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StateCacheState state cache state
//
// swagger:model state.CacheState
type StateCacheState struct {

	// capacity
	Capacity int64 `json:"capacity,omitempty"`

	// filled
	Filled int64 `json:"filled,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// pieces
	Pieces map[string]StateItemState `json:"pieces,omitempty"`

	// pieces count
	PiecesCount int64 `json:"piecesCount,omitempty"`

	// pieces length
	PiecesLength int64 `json:"piecesLength,omitempty"`

	// readers
	Readers []*StateReaderState `json:"readers"`

	// torrent
	Torrent *StateTorrentStatus `json:"torrent,omitempty"`
}

// Validate validates this state cache state
func (m *StateCacheState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePieces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReaders(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTorrent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StateCacheState) validatePieces(formats strfmt.Registry) error {
	if swag.IsZero(m.Pieces) { // not required
		return nil
	}

	for k := range m.Pieces {

		if err := validate.Required("pieces"+"."+k, "body", m.Pieces[k]); err != nil {
			return err
		}
		if val, ok := m.Pieces[k]; ok {
			if err := val.Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("pieces" + "." + k)
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("pieces" + "." + k)
				}

				return err
			}
		}

	}

	return nil
}

func (m *StateCacheState) validateReaders(formats strfmt.Registry) error {
	if swag.IsZero(m.Readers) { // not required
		return nil
	}

	for i := 0; i < len(m.Readers); i++ {
		if swag.IsZero(m.Readers[i]) { // not required
			continue
		}

		if m.Readers[i] != nil {
			if err := m.Readers[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("readers" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("readers" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *StateCacheState) validateTorrent(formats strfmt.Registry) error {
	if swag.IsZero(m.Torrent) { // not required
		return nil
	}

	if m.Torrent != nil {
		if err := m.Torrent.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("torrent")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("torrent")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this state cache state based on the context it is used
func (m *StateCacheState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePieces(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReaders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTorrent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StateCacheState) contextValidatePieces(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Pieces {

		if val, ok := m.Pieces[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *StateCacheState) contextValidateReaders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Readers); i++ {

		if m.Readers[i] != nil {

			if swag.IsZero(m.Readers[i]) { // not required
				return nil
			}

			if err := m.Readers[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("readers" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("readers" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *StateCacheState) contextValidateTorrent(ctx context.Context, formats strfmt.Registry) error {

	if m.Torrent != nil {

		if swag.IsZero(m.Torrent) { // not required
			return nil
		}

		if err := m.Torrent.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("torrent")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("torrent")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StateCacheState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateCacheState) UnmarshalBinary(b []byte) error {
	var res StateCacheState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
