// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// StateTorrentStat state torrent stat
//
// swagger:model state.TorrentStat
type StateTorrentStat int64

// for schema
var stateTorrentStatEnum []any

func init() {
	var res []StateTorrentStat
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		stateTorrentStatEnum = append(stateTorrentStatEnum, v)
	}
}

func (m StateTorrentStat) validateStateTorrentStatEnum(path, location string, value StateTorrentStat) error {
	if err := validate.EnumCase(path, location, value, stateTorrentStatEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this state torrent stat
func (m StateTorrentStat) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateStateTorrentStatEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this state torrent stat based on context it is used
func (m StateTorrentStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
