// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StateTorrentStatus state torrent status
//
// swagger:model state.TorrentStatus
type StateTorrentStatus struct {

	// active peers
	ActivePeers int64 `json:"active_peers,omitempty"`

	// bit rate
	BitRate string `json:"bit_rate,omitempty"`

	// bytes read
	BytesRead int64 `json:"bytes_read,omitempty"`

	// bytes read data
	BytesReadData int64 `json:"bytes_read_data,omitempty"`

	// bytes read useful data
	BytesReadUsefulData int64 `json:"bytes_read_useful_data,omitempty"`

	// bytes written
	BytesWritten int64 `json:"bytes_written,omitempty"`

	// bytes written data
	BytesWrittenData int64 `json:"bytes_written_data,omitempty"`

	// category
	Category string `json:"category,omitempty"`

	// chunks read
	ChunksRead int64 `json:"chunks_read,omitempty"`

	// chunks read useful
	ChunksReadUseful int64 `json:"chunks_read_useful,omitempty"`

	// chunks read wasted
	ChunksReadWasted int64 `json:"chunks_read_wasted,omitempty"`

	// chunks written
	ChunksWritten int64 `json:"chunks_written,omitempty"`

	// connected seeders
	ConnectedSeeders int64 `json:"connected_seeders,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// download speed
	DownloadSpeed float64 `json:"download_speed,omitempty"`

	// duration seconds
	DurationSeconds float64 `json:"duration_seconds,omitempty"`

	// file stats
	FileStats []*StateTorrentFileStat `json:"file_stats"`

	// half open peers
	HalfOpenPeers int64 `json:"half_open_peers,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// loaded size
	LoadedSize int64 `json:"loaded_size,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pending peers
	PendingPeers int64 `json:"pending_peers,omitempty"`

	// pieces dirtied bad
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad,omitempty"`

	// pieces dirtied good
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good,omitempty"`

	// poster
	Poster string `json:"poster,omitempty"`

	// preload size
	PreloadSize int64 `json:"preload_size,omitempty"`

	// preloaded bytes
	PreloadedBytes int64 `json:"preloaded_bytes,omitempty"`

	// stat
	Stat StateTorrentStat `json:"stat,omitempty"`

	// stat string
	StatString string `json:"stat_string,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// torrent size
	TorrentSize int64 `json:"torrent_size,omitempty"`

	// total peers
	TotalPeers int64 `json:"total_peers,omitempty"`

	// upload speed
	UploadSpeed float64 `json:"upload_speed,omitempty"`
}

// Validate validates this state torrent status
func (m *StateTorrentStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFileStats(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StateTorrentStatus) validateFileStats(formats strfmt.Registry) error {
	if swag.IsZero(m.FileStats) { // not required
		return nil
	}

	for i := 0; i < len(m.FileStats); i++ {
		if swag.IsZero(m.FileStats[i]) { // not required
			continue
		}

		if m.FileStats[i] != nil {
			if err := m.FileStats[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("file_stats" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("file_stats" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *StateTorrentStatus) validateStat(formats strfmt.Registry) error {
	if swag.IsZero(m.Stat) { // not required
		return nil
	}

	if err := m.Stat.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("stat")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("stat")
		}

		return err
	}

	return nil
}

// ContextValidate validate this state torrent status based on the context it is used
func (m *StateTorrentStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFileStats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StateTorrentStatus) contextValidateFileStats(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FileStats); i++ {

		if m.FileStats[i] != nil {

			if swag.IsZero(m.FileStats[i]) { // not required
				return nil
			}

			if err := m.FileStats[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("file_stats" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("file_stats" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *StateTorrentStatus) contextValidateStat(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Stat) { // not required
		return nil
	}

	if err := m.Stat.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("stat")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("stat")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StateTorrentStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateTorrentStatus) UnmarshalBinary(b []byte) error {
	var res StateTorrentStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
