// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StateReaderState state reader state
//
// swagger:model state.ReaderState
type StateReaderState struct {

	// end
	End int64 `json:"end,omitempty"`

	// reader
	Reader int64 `json:"reader,omitempty"`

	// start
	Start int64 `json:"start,omitempty"`
}

// Validate validates this state reader state
func (m *StateReaderState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this state reader state based on context it is used
func (m *StateReaderState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StateReaderState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateReaderState) UnmarshalBinary(b []byte) error {
	var res StateReaderState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
