// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StateTorrentFileStat state torrent file stat
//
// swagger:model state.TorrentFileStat
type StateTorrentFileStat struct {

	// id
	ID int64 `json:"id,omitempty"`

	// length
	Length int64 `json:"length,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this state torrent file stat
func (m *StateTorrentFileStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this state torrent file stat based on context it is used
func (m *StateTorrentFileStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StateTorrentFileStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateTorrentFileStat) UnmarshalBinary(b []byte) error {
	var res StateTorrentFileStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
