// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new api API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new api API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new api API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for api API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeMultipartFormData sets the Content-Type header to "multipart/form-data".
func WithContentTypeMultipartFormData(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"multipart/form-data"}
}

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationOctetStream sets the Accept header to "application/octet-stream".
func WithAcceptApplicationOctetStream(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/octet-stream"}
}

// WithAcceptAudioxMpegurl sets the Accept header to "audio/x-mpegurl".
func WithAcceptAudioxMpegurl(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"audio/x-mpegurl"}
}

// WithAcceptTextPlain sets the Accept header to "text/plain".
func WithAcceptTextPlain(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetDownloadSize(params *GetDownloadSizeParams, writer io.Writer, opts ...ClientOption) (*GetDownloadSizeOK, error)

	GetEcho(params *GetEchoParams, opts ...ClientOption) (*GetEchoOK, error)

	GetFfpHashID(params *GetFfpHashIDParams, opts ...ClientOption) (*GetFfpHashIDOK, error)

	GetPlayHashID(params *GetPlayHashIDParams, opts ...ClientOption) (*GetPlayHashIDOK, error)

	GetPlaylist(params *GetPlaylistParams, writer io.Writer, opts ...ClientOption) (*GetPlaylistOK, error)

	GetPlaylistallAllM3u(params *GetPlaylistallAllM3uParams, writer io.Writer, opts ...ClientOption) (*GetPlaylistallAllM3uOK, error)

	GetSearch(params *GetSearchParams, opts ...ClientOption) (*GetSearchOK, error)

	GetShutdown(params *GetShutdownParams, opts ...ClientOption) (*GetShutdownOK, error)

	GetStorageSettings(params *GetStorageSettingsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStorageSettingsOK, error)

	GetStream(params *GetStreamParams, opts ...ClientOption) (*GetStreamOK, error)

	GetTorznabSearch(params *GetTorznabSearchParams, opts ...ClientOption) (*GetTorznabSearchOK, error)

	PostSettings(params *PostSettingsParams, opts ...ClientOption) (*PostSettingsOK, error)

	PostTorrentUpload(params *PostTorrentUploadParams, opts ...ClientOption) (*PostTorrentUploadOK, error)

	PostTorrents(params *PostTorrentsParams, opts ...ClientOption) (*PostTorrentsOK, error)

	PostViewed(params *PostViewedParams, opts ...ClientOption) (*PostViewedOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetDownloadSize generates test file of given size

Download the test file of given size (for speed testing purpose).
*/
func (a *Client) GetDownloadSize(params *GetDownloadSizeParams, writer io.Writer, opts ...ClientOption) (*GetDownloadSizeOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetDownloadSizeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetDownloadSize",
		Method:             "GET",
		PathPattern:        "/download/{size}",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetDownloadSizeReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetDownloadSizeOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetDownloadSize: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetEcho tests server status

Tests whether server is alive or not
*/
func (a *Client) GetEcho(params *GetEchoParams, opts ...ClientOption) (*GetEchoOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetEchoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetEcho",
		Method:             "GET",
		PathPattern:        "/echo",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetEchoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetEchoOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetEcho: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetFfpHashID gathers informations using ffprobe

Gather informations using ffprobe.
*/
func (a *Client) GetFfpHashID(params *GetFfpHashIDParams, opts ...ClientOption) (*GetFfpHashIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetFfpHashIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFfpHashID",
		Method:             "GET",
		PathPattern:        "/ffp/{hash}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetFfpHashIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetFfpHashIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFfpHashID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetPlayHashID plays given torrent by infohash

Play given torrent referenced by infohash and file id.
*/
func (a *Client) GetPlayHashID(params *GetPlayHashIDParams, opts ...ClientOption) (*GetPlayHashIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPlayHashIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPlayHashID",
		Method:             "GET",
		PathPattern:        "/play/{hash}/{id}",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPlayHashIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPlayHashIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPlayHashID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetPlaylist gets HTTP link of torrent in m3 u list

Get HTTP link of torrent in M3U list.
*/
func (a *Client) GetPlaylist(params *GetPlaylistParams, writer io.Writer, opts ...ClientOption) (*GetPlaylistOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPlaylistParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPlaylist",
		Method:             "GET",
		PathPattern:        "/playlist",
		ProducesMediaTypes: []string{"audio/x-mpegurl"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPlaylistReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPlaylistOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPlaylist: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetPlaylistallAllM3u gets a m3 u playlist with all torrents

Retrieve all torrents and generates a bundled M3U playlist.
*/
func (a *Client) GetPlaylistallAllM3u(params *GetPlaylistallAllM3uParams, writer io.Writer, opts ...ClientOption) (*GetPlaylistallAllM3uOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPlaylistallAllM3uParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPlaylistallAllM3u",
		Method:             "GET",
		PathPattern:        "/playlistall/all.m3u",
		ProducesMediaTypes: []string{"audio/x-mpegurl"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPlaylistallAllM3uReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPlaylistallAllM3uOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPlaylistallAllM3u: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSearch makes a rutor search

Makes a rutor search.
*/
func (a *Client) GetSearch(params *GetSearchParams, opts ...ClientOption) (*GetSearchOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSearch",
		Method:             "GET",
		PathPattern:        "/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetSearchOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetShutdown shuts down server

Gracefully shuts down server after 1 second.
*/
func (a *Client) GetShutdown(params *GetShutdownParams, opts ...ClientOption) (*GetShutdownOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetShutdownParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetShutdown",
		Method:             "GET",
		PathPattern:        "/shutdown",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetShutdownReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetShutdownOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetShutdown: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetStorageSettings gets storage configuration settings

Retrieves the current storage preferences for settings and viewed history
*/
func (a *Client) GetStorageSettings(params *GetStorageSettingsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStorageSettingsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetStorageSettingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStorageSettings",
		Method:             "GET",
		PathPattern:        "/storage/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStorageSettingsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetStorageSettingsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStorageSettings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetStream multis usage endpoint

Multi usage endpoint.
*/
func (a *Client) GetStream(params *GetStreamParams, opts ...ClientOption) (*GetStreamOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetStreamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStream",
		Method:             "GET",
		PathPattern:        "/stream",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStreamReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetStreamOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetStream: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTorznabSearch makes a torznab search

Makes a torznab search.
*/
func (a *Client) GetTorznabSearch(params *GetTorznabSearchParams, opts ...ClientOption) (*GetTorznabSearchOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTorznabSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetTorznabSearch",
		Method:             "GET",
		PathPattern:        "/torznab/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTorznabSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTorznabSearchOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetTorznabSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostSettings gets set server settings

Allow to get or set server settings.
*/
func (a *Client) PostSettings(params *PostSettingsParams, opts ...ClientOption) (*PostSettingsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostSettingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostSettings",
		Method:             "POST",
		PathPattern:        "/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostSettingsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostSettingsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostSettings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostTorrentUpload adds torrent file

Only one file support.
*/
func (a *Client) PostTorrentUpload(params *PostTorrentUploadParams, opts ...ClientOption) (*PostTorrentUploadOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostTorrentUploadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostTorrentUpload",
		Method:             "POST",
		PathPattern:        "/torrent/upload",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostTorrentUploadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostTorrentUploadOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostTorrentUpload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostTorrents handles torrents informations

Allow to list, add, remove, get, set, drop, wipe torrents on server. The action depends of what has been asked.
*/
func (a *Client) PostTorrents(params *PostTorrentsParams, opts ...ClientOption) (*PostTorrentsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostTorrentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostTorrents",
		Method:             "POST",
		PathPattern:        "/torrents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostTorrentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostTorrentsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostTorrents: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostViewed sets list remove viewed torrents

Allow to set, list or remove viewed torrents from server.
*/
func (a *Client) PostViewed(params *PostViewedParams, opts ...ClientOption) (*PostViewedOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostViewedParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostViewed",
		Method:             "POST",
		PathPattern:        "/viewed",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostViewedReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostViewedOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostViewed: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
