// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTorznabSearchParams creates a new GetTorznabSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTorznabSearchParams() *GetTorznabSearchParams {
	return &GetTorznabSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTorznabSearchParamsWithTimeout creates a new GetTorznabSearchParams object
// with the ability to set a timeout on a request.
func NewGetTorznabSearchParamsWithTimeout(timeout time.Duration) *GetTorznabSearchParams {
	return &GetTorznabSearchParams{
		timeout: timeout,
	}
}

// NewGetTorznabSearchParamsWithContext creates a new GetTorznabSearchParams object
// with the ability to set a context for a request.
func NewGetTorznabSearchParamsWithContext(ctx context.Context) *GetTorznabSearchParams {
	return &GetTorznabSearchParams{
		Context: ctx,
	}
}

// NewGetTorznabSearchParamsWithHTTPClient creates a new GetTorznabSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTorznabSearchParamsWithHTTPClient(client *http.Client) *GetTorznabSearchParams {
	return &GetTorznabSearchParams{
		HTTPClient: client,
	}
}

/*
GetTorznabSearchParams contains all the parameters to send to the API endpoint

	for the get torznab search operation.

	Typically these are written to a http.Request.
*/
type GetTorznabSearchParams struct {

	/* Query.

	   Torznab query
	*/
	Query string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get torznab search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTorznabSearchParams) WithDefaults() *GetTorznabSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get torznab search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTorznabSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get torznab search params
func (o *GetTorznabSearchParams) WithTimeout(timeout time.Duration) *GetTorznabSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get torznab search params
func (o *GetTorznabSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get torznab search params
func (o *GetTorznabSearchParams) WithContext(ctx context.Context) *GetTorznabSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get torznab search params
func (o *GetTorznabSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get torznab search params
func (o *GetTorznabSearchParams) WithHTTPClient(client *http.Client) *GetTorznabSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get torznab search params
func (o *GetTorznabSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the get torznab search params
func (o *GetTorznabSearchParams) WithQuery(query string) *GetTorznabSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get torznab search params
func (o *GetTorznabSearchParams) SetQuery(query string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *GetTorznabSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {

		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
