// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetEchoReader is a Reader for the GetEcho structure.
type GetEchoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEchoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetEchoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /echo] GetEcho", response, response.Code())
	}
}

// NewGetEchoOK creates a GetEchoOK with default headers values
func NewGetEchoOK() *GetEchoOK {
	return &GetEchoOK{}
}

/*
GetEchoOK describes a response with status code 200, with default header values.

Server version
*/
type GetEchoOK struct {
	Payload string
}

// IsSuccess returns true when this get echo o k response has a 2xx status code
func (o *GetEchoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get echo o k response has a 3xx status code
func (o *GetEchoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get echo o k response has a 4xx status code
func (o *GetEchoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get echo o k response has a 5xx status code
func (o *GetEchoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get echo o k response a status code equal to that given
func (o *GetEchoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get echo o k response
func (o *GetEchoOK) Code() int {
	return 200
}

func (o *GetEchoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /echo][%d] getEchoOK %s", 200, payload)
}

func (o *GetEchoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /echo][%d] getEchoOK %s", 200, payload)
}

func (o *GetEchoOK) GetPayload() string {
	return o.Payload
}

func (o *GetEchoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
