// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/v4/pkg/torrserver/models"
)

// GetTorznabSearchReader is a Reader for the GetTorznabSearch structure.
type GetTorznabSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTorznabSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetTorznabSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /torznab/search] GetTorznabSearch", response, response.Code())
	}
}

// NewGetTorznabSearchOK creates a GetTorznabSearchOK with default headers values
func NewGetTorznabSearchOK() *GetTorznabSearchOK {
	return &GetTorznabSearchOK{}
}

/*
GetTorznabSearchOK describes a response with status code 200, with default header values.

Torznab torrent search result(s)
*/
type GetTorznabSearchOK struct {
	Payload []*models.ModelsTorrentDetails
}

// IsSuccess returns true when this get torznab search o k response has a 2xx status code
func (o *GetTorznabSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get torznab search o k response has a 3xx status code
func (o *GetTorznabSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get torznab search o k response has a 4xx status code
func (o *GetTorznabSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get torznab search o k response has a 5xx status code
func (o *GetTorznabSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get torznab search o k response a status code equal to that given
func (o *GetTorznabSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get torznab search o k response
func (o *GetTorznabSearchOK) Code() int {
	return 200
}

func (o *GetTorznabSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /torznab/search][%d] getTorznabSearchOK %s", 200, payload)
}

func (o *GetTorznabSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /torznab/search][%d] getTorznabSearchOK %s", 200, payload)
}

func (o *GetTorznabSearchOK) GetPayload() []*models.ModelsTorrentDetails {
	return o.Payload
}

func (o *GetTorznabSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
