// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPlaylistallAllM3uReader is a Reader for the GetPlaylistallAllM3u structure.
type GetPlaylistallAllM3uReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetPlaylistallAllM3uReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlaylistallAllM3uOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /playlistall/all.m3u] GetPlaylistallAllM3u", response, response.Code())
	}
}

// NewGetPlaylistallAllM3uOK creates a GetPlaylistallAllM3uOK with default headers values
func NewGetPlaylistallAllM3uOK(writer io.Writer) *GetPlaylistallAllM3uOK {
	return &GetPlaylistallAllM3uOK{

		Payload: writer,
	}
}

/*
GetPlaylistallAllM3uOK describes a response with status code 200, with default header values.

OK
*/
type GetPlaylistallAllM3uOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get playlistall all m3u o k response has a 2xx status code
func (o *GetPlaylistallAllM3uOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get playlistall all m3u o k response has a 3xx status code
func (o *GetPlaylistallAllM3uOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get playlistall all m3u o k response has a 4xx status code
func (o *GetPlaylistallAllM3uOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get playlistall all m3u o k response has a 5xx status code
func (o *GetPlaylistallAllM3uOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get playlistall all m3u o k response a status code equal to that given
func (o *GetPlaylistallAllM3uOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get playlistall all m3u o k response
func (o *GetPlaylistallAllM3uOK) Code() int {
	return 200
}

func (o *GetPlaylistallAllM3uOK) Error() string {
	return fmt.Sprintf("[GET /playlistall/all.m3u][%d] getPlaylistallAllM3uOK", 200)
}

func (o *GetPlaylistallAllM3uOK) String() string {
	return fmt.Sprintf("[GET /playlistall/all.m3u][%d] getPlaylistallAllM3uOK", 200)
}

func (o *GetPlaylistallAllM3uOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetPlaylistallAllM3uOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
