// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFfpHashIDParams creates a new GetFfpHashIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFfpHashIDParams() *GetFfpHashIDParams {
	return &GetFfpHashIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFfpHashIDParamsWithTimeout creates a new GetFfpHashIDParams object
// with the ability to set a timeout on a request.
func NewGetFfpHashIDParamsWithTimeout(timeout time.Duration) *GetFfpHashIDParams {
	return &GetFfpHashIDParams{
		timeout: timeout,
	}
}

// NewGetFfpHashIDParamsWithContext creates a new GetFfpHashIDParams object
// with the ability to set a context for a request.
func NewGetFfpHashIDParamsWithContext(ctx context.Context) *GetFfpHashIDParams {
	return &GetFfpHashIDParams{
		Context: ctx,
	}
}

// NewGetFfpHashIDParamsWithHTTPClient creates a new GetFfpHashIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFfpHashIDParamsWithHTTPClient(client *http.Client) *GetFfpHashIDParams {
	return &GetFfpHashIDParams{
		HTTPClient: client,
	}
}

/*
GetFfpHashIDParams contains all the parameters to send to the API endpoint

	for the get ffp hash ID operation.

	Typically these are written to a http.Request.
*/
type GetFfpHashIDParams struct {

	/* Hash.

	   Torrent hash
	*/
	Hash string

	/* ID.

	   File index in torrent
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ffp hash ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFfpHashIDParams) WithDefaults() *GetFfpHashIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ffp hash ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFfpHashIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ffp hash ID params
func (o *GetFfpHashIDParams) WithTimeout(timeout time.Duration) *GetFfpHashIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ffp hash ID params
func (o *GetFfpHashIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ffp hash ID params
func (o *GetFfpHashIDParams) WithContext(ctx context.Context) *GetFfpHashIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ffp hash ID params
func (o *GetFfpHashIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ffp hash ID params
func (o *GetFfpHashIDParams) WithHTTPClient(client *http.Client) *GetFfpHashIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ffp hash ID params
func (o *GetFfpHashIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHash adds the hash to the get ffp hash ID params
func (o *GetFfpHashIDParams) WithHash(hash string) *GetFfpHashIDParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get ffp hash ID params
func (o *GetFfpHashIDParams) SetHash(hash string) {
	o.Hash = hash
}

// WithID adds the id to the get ffp hash ID params
func (o *GetFfpHashIDParams) WithID(id string) *GetFfpHashIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ffp hash ID params
func (o *GetFfpHashIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFfpHashIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hash
	if err := r.SetPathParam("hash", o.Hash); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
