// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStorageSettingsParams creates a new GetStorageSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStorageSettingsParams() *GetStorageSettingsParams {
	return &GetStorageSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStorageSettingsParamsWithTimeout creates a new GetStorageSettingsParams object
// with the ability to set a timeout on a request.
func NewGetStorageSettingsParamsWithTimeout(timeout time.Duration) *GetStorageSettingsParams {
	return &GetStorageSettingsParams{
		timeout: timeout,
	}
}

// NewGetStorageSettingsParamsWithContext creates a new GetStorageSettingsParams object
// with the ability to set a context for a request.
func NewGetStorageSettingsParamsWithContext(ctx context.Context) *GetStorageSettingsParams {
	return &GetStorageSettingsParams{
		Context: ctx,
	}
}

// NewGetStorageSettingsParamsWithHTTPClient creates a new GetStorageSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStorageSettingsParamsWithHTTPClient(client *http.Client) *GetStorageSettingsParams {
	return &GetStorageSettingsParams{
		HTTPClient: client,
	}
}

/*
GetStorageSettingsParams contains all the parameters to send to the API endpoint

	for the get storage settings operation.

	Typically these are written to a http.Request.
*/
type GetStorageSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get storage settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStorageSettingsParams) WithDefaults() *GetStorageSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get storage settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStorageSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get storage settings params
func (o *GetStorageSettingsParams) WithTimeout(timeout time.Duration) *GetStorageSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get storage settings params
func (o *GetStorageSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get storage settings params
func (o *GetStorageSettingsParams) WithContext(ctx context.Context) *GetStorageSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get storage settings params
func (o *GetStorageSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get storage settings params
func (o *GetStorageSettingsParams) WithHTTPClient(client *http.Client) *GetStorageSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get storage settings params
func (o *GetStorageSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStorageSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
