// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlayHashIDParams creates a new GetPlayHashIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlayHashIDParams() *GetPlayHashIDParams {
	return &GetPlayHashIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlayHashIDParamsWithTimeout creates a new GetPlayHashIDParams object
// with the ability to set a timeout on a request.
func NewGetPlayHashIDParamsWithTimeout(timeout time.Duration) *GetPlayHashIDParams {
	return &GetPlayHashIDParams{
		timeout: timeout,
	}
}

// NewGetPlayHashIDParamsWithContext creates a new GetPlayHashIDParams object
// with the ability to set a context for a request.
func NewGetPlayHashIDParamsWithContext(ctx context.Context) *GetPlayHashIDParams {
	return &GetPlayHashIDParams{
		Context: ctx,
	}
}

// NewGetPlayHashIDParamsWithHTTPClient creates a new GetPlayHashIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlayHashIDParamsWithHTTPClient(client *http.Client) *GetPlayHashIDParams {
	return &GetPlayHashIDParams{
		HTTPClient: client,
	}
}

/*
GetPlayHashIDParams contains all the parameters to send to the API endpoint

	for the get play hash ID operation.

	Typically these are written to a http.Request.
*/
type GetPlayHashIDParams struct {

	/* Hash.

	   Torrent infohash
	*/
	Hash string

	/* ID.

	   File index in torrent
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get play hash ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlayHashIDParams) WithDefaults() *GetPlayHashIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get play hash ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlayHashIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get play hash ID params
func (o *GetPlayHashIDParams) WithTimeout(timeout time.Duration) *GetPlayHashIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get play hash ID params
func (o *GetPlayHashIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get play hash ID params
func (o *GetPlayHashIDParams) WithContext(ctx context.Context) *GetPlayHashIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get play hash ID params
func (o *GetPlayHashIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get play hash ID params
func (o *GetPlayHashIDParams) WithHTTPClient(client *http.Client) *GetPlayHashIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get play hash ID params
func (o *GetPlayHashIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHash adds the hash to the get play hash ID params
func (o *GetPlayHashIDParams) WithHash(hash string) *GetPlayHashIDParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get play hash ID params
func (o *GetPlayHashIDParams) SetHash(hash string) {
	o.Hash = hash
}

// WithID adds the id to the get play hash ID params
func (o *GetPlayHashIDParams) WithID(id string) *GetPlayHashIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get play hash ID params
func (o *GetPlayHashIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlayHashIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hash
	if err := r.SetPathParam("hash", o.Hash); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
