// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetStorageSettingsReader is a Reader for the GetStorageSettings structure.
type GetStorageSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStorageSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetStorageSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetStorageSettingsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetStorageSettingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /storage/settings] GetStorageSettings", response, response.Code())
	}
}

// NewGetStorageSettingsOK creates a GetStorageSettingsOK with default headers values
func NewGetStorageSettingsOK() *GetStorageSettingsOK {
	return &GetStorageSettingsOK{}
}

/*
GetStorageSettingsOK describes a response with status code 200, with default header values.

Storage preferences
*/
type GetStorageSettingsOK struct {
	Payload any
}

// IsSuccess returns true when this get storage settings o k response has a 2xx status code
func (o *GetStorageSettingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get storage settings o k response has a 3xx status code
func (o *GetStorageSettingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get storage settings o k response has a 4xx status code
func (o *GetStorageSettingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get storage settings o k response has a 5xx status code
func (o *GetStorageSettingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get storage settings o k response a status code equal to that given
func (o *GetStorageSettingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get storage settings o k response
func (o *GetStorageSettingsOK) Code() int {
	return 200
}

func (o *GetStorageSettingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsOK %s", 200, payload)
}

func (o *GetStorageSettingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsOK %s", 200, payload)
}

func (o *GetStorageSettingsOK) GetPayload() any {
	return o.Payload
}

func (o *GetStorageSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStorageSettingsUnauthorized creates a GetStorageSettingsUnauthorized with default headers values
func NewGetStorageSettingsUnauthorized() *GetStorageSettingsUnauthorized {
	return &GetStorageSettingsUnauthorized{}
}

/*
GetStorageSettingsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetStorageSettingsUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get storage settings unauthorized response has a 2xx status code
func (o *GetStorageSettingsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get storage settings unauthorized response has a 3xx status code
func (o *GetStorageSettingsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get storage settings unauthorized response has a 4xx status code
func (o *GetStorageSettingsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get storage settings unauthorized response has a 5xx status code
func (o *GetStorageSettingsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get storage settings unauthorized response a status code equal to that given
func (o *GetStorageSettingsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get storage settings unauthorized response
func (o *GetStorageSettingsUnauthorized) Code() int {
	return 401
}

func (o *GetStorageSettingsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsUnauthorized %s", 401, payload)
}

func (o *GetStorageSettingsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsUnauthorized %s", 401, payload)
}

func (o *GetStorageSettingsUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetStorageSettingsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetStorageSettingsInternalServerError creates a GetStorageSettingsInternalServerError with default headers values
func NewGetStorageSettingsInternalServerError() *GetStorageSettingsInternalServerError {
	return &GetStorageSettingsInternalServerError{}
}

/*
GetStorageSettingsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetStorageSettingsInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get storage settings internal server error response has a 2xx status code
func (o *GetStorageSettingsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get storage settings internal server error response has a 3xx status code
func (o *GetStorageSettingsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get storage settings internal server error response has a 4xx status code
func (o *GetStorageSettingsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get storage settings internal server error response has a 5xx status code
func (o *GetStorageSettingsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get storage settings internal server error response a status code equal to that given
func (o *GetStorageSettingsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get storage settings internal server error response
func (o *GetStorageSettingsInternalServerError) Code() int {
	return 500
}

func (o *GetStorageSettingsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsInternalServerError %s", 500, payload)
}

func (o *GetStorageSettingsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /storage/settings][%d] getStorageSettingsInternalServerError %s", 500, payload)
}

func (o *GetStorageSettingsInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetStorageSettingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
