// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlaylistallAllM3uParams creates a new GetPlaylistallAllM3uParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlaylistallAllM3uParams() *GetPlaylistallAllM3uParams {
	return &GetPlaylistallAllM3uParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlaylistallAllM3uParamsWithTimeout creates a new GetPlaylistallAllM3uParams object
// with the ability to set a timeout on a request.
func NewGetPlaylistallAllM3uParamsWithTimeout(timeout time.Duration) *GetPlaylistallAllM3uParams {
	return &GetPlaylistallAllM3uParams{
		timeout: timeout,
	}
}

// NewGetPlaylistallAllM3uParamsWithContext creates a new GetPlaylistallAllM3uParams object
// with the ability to set a context for a request.
func NewGetPlaylistallAllM3uParamsWithContext(ctx context.Context) *GetPlaylistallAllM3uParams {
	return &GetPlaylistallAllM3uParams{
		Context: ctx,
	}
}

// NewGetPlaylistallAllM3uParamsWithHTTPClient creates a new GetPlaylistallAllM3uParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlaylistallAllM3uParamsWithHTTPClient(client *http.Client) *GetPlaylistallAllM3uParams {
	return &GetPlaylistallAllM3uParams{
		HTTPClient: client,
	}
}

/*
GetPlaylistallAllM3uParams contains all the parameters to send to the API endpoint

	for the get playlistall all m3u operation.

	Typically these are written to a http.Request.
*/
type GetPlaylistallAllM3uParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get playlistall all m3u params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlaylistallAllM3uParams) WithDefaults() *GetPlaylistallAllM3uParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get playlistall all m3u params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlaylistallAllM3uParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) WithTimeout(timeout time.Duration) *GetPlaylistallAllM3uParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) WithContext(ctx context.Context) *GetPlaylistallAllM3uParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) WithHTTPClient(client *http.Client) *GetPlaylistallAllM3uParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get playlistall all m3u params
func (o *GetPlaylistallAllM3uParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlaylistallAllM3uParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
