// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDownloadSizeParams creates a new GetDownloadSizeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDownloadSizeParams() *GetDownloadSizeParams {
	return &GetDownloadSizeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDownloadSizeParamsWithTimeout creates a new GetDownloadSizeParams object
// with the ability to set a timeout on a request.
func NewGetDownloadSizeParamsWithTimeout(timeout time.Duration) *GetDownloadSizeParams {
	return &GetDownloadSizeParams{
		timeout: timeout,
	}
}

// NewGetDownloadSizeParamsWithContext creates a new GetDownloadSizeParams object
// with the ability to set a context for a request.
func NewGetDownloadSizeParamsWithContext(ctx context.Context) *GetDownloadSizeParams {
	return &GetDownloadSizeParams{
		Context: ctx,
	}
}

// NewGetDownloadSizeParamsWithHTTPClient creates a new GetDownloadSizeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDownloadSizeParamsWithHTTPClient(client *http.Client) *GetDownloadSizeParams {
	return &GetDownloadSizeParams{
		HTTPClient: client,
	}
}

/*
GetDownloadSizeParams contains all the parameters to send to the API endpoint

	for the get download size operation.

	Typically these are written to a http.Request.
*/
type GetDownloadSizeParams struct {

	/* Size.

	   Test file size (in MB)
	*/
	Size string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get download size params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDownloadSizeParams) WithDefaults() *GetDownloadSizeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get download size params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDownloadSizeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get download size params
func (o *GetDownloadSizeParams) WithTimeout(timeout time.Duration) *GetDownloadSizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get download size params
func (o *GetDownloadSizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get download size params
func (o *GetDownloadSizeParams) WithContext(ctx context.Context) *GetDownloadSizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get download size params
func (o *GetDownloadSizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get download size params
func (o *GetDownloadSizeParams) WithHTTPClient(client *http.Client) *GetDownloadSizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get download size params
func (o *GetDownloadSizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSize adds the size to the get download size params
func (o *GetDownloadSizeParams) WithSize(size string) *GetDownloadSizeParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get download size params
func (o *GetDownloadSizeParams) SetSize(size string) {
	o.Size = size
}

// WriteToRequest writes these params to a swagger request
func (o *GetDownloadSizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param size
	if err := r.SetPathParam("size", o.Size); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
