// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetStreamReader is a Reader for the GetStream structure.
type GetStreamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStreamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetStreamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /stream] GetStream", response, response.Code())
	}
}

// NewGetStreamOK creates a GetStreamOK with default headers values
func NewGetStreamOK() *GetStreamOK {
	return &GetStreamOK{}
}

/*
GetStreamOK describes a response with status code 200, with default header values.

Data returned according to query
*/
type GetStreamOK struct {
}

// IsSuccess returns true when this get stream o k response has a 2xx status code
func (o *GetStreamOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get stream o k response has a 3xx status code
func (o *GetStreamOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get stream o k response has a 4xx status code
func (o *GetStreamOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get stream o k response has a 5xx status code
func (o *GetStreamOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get stream o k response a status code equal to that given
func (o *GetStreamOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get stream o k response
func (o *GetStreamOK) Code() int {
	return 200
}

func (o *GetStreamOK) Error() string {
	return fmt.Sprintf("[GET /stream][%d] getStreamOK", 200)
}

func (o *GetStreamOK) String() string {
	return fmt.Sprintf("[GET /stream][%d] getStreamOK", 200)
}

func (o *GetStreamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
