// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStreamParams creates a new GetStreamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStreamParams() *GetStreamParams {
	return &GetStreamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStreamParamsWithTimeout creates a new GetStreamParams object
// with the ability to set a timeout on a request.
func NewGetStreamParamsWithTimeout(timeout time.Duration) *GetStreamParams {
	return &GetStreamParams{
		timeout: timeout,
	}
}

// NewGetStreamParamsWithContext creates a new GetStreamParams object
// with the ability to set a context for a request.
func NewGetStreamParamsWithContext(ctx context.Context) *GetStreamParams {
	return &GetStreamParams{
		Context: ctx,
	}
}

// NewGetStreamParamsWithHTTPClient creates a new GetStreamParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStreamParamsWithHTTPClient(client *http.Client) *GetStreamParams {
	return &GetStreamParams{
		HTTPClient: client,
	}
}

/*
GetStreamParams contains all the parameters to send to the API endpoint

	for the get stream operation.

	Typically these are written to a http.Request.
*/
type GetStreamParams struct {

	/* Category.

	   Set category of torrent, used in web: movie, tv, music, other
	*/
	Category *string

	/* Fromlast.

	   Get M3U from last played file
	*/
	Fromlast *string

	/* Index.

	   File index in torrent
	*/
	Index *string

	/* Link.

	   Magnet/hash/link to torrent
	*/
	Link string

	/* M3u.

	   Get torrent as M3U playlist
	*/
	M3u *string

	/* Play.

	   Start stream torrent
	*/
	Play *string

	/* Poster.

	   Set poster link of torrent
	*/
	Poster *string

	/* Preload.

	   Should preload torrent
	*/
	Preload *string

	/* Save.

	   Should save torrent
	*/
	Save *string

	/* Stat.

	   Get statistics from torrent
	*/
	Stat *string

	/* Title.

	   Set title of torrent
	*/
	Title *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStreamParams) WithDefaults() *GetStreamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStreamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get stream params
func (o *GetStreamParams) WithTimeout(timeout time.Duration) *GetStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stream params
func (o *GetStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stream params
func (o *GetStreamParams) WithContext(ctx context.Context) *GetStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stream params
func (o *GetStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stream params
func (o *GetStreamParams) WithHTTPClient(client *http.Client) *GetStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stream params
func (o *GetStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get stream params
func (o *GetStreamParams) WithCategory(category *string) *GetStreamParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get stream params
func (o *GetStreamParams) SetCategory(category *string) {
	o.Category = category
}

// WithFromlast adds the fromlast to the get stream params
func (o *GetStreamParams) WithFromlast(fromlast *string) *GetStreamParams {
	o.SetFromlast(fromlast)
	return o
}

// SetFromlast adds the fromlast to the get stream params
func (o *GetStreamParams) SetFromlast(fromlast *string) {
	o.Fromlast = fromlast
}

// WithIndex adds the index to the get stream params
func (o *GetStreamParams) WithIndex(index *string) *GetStreamParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the get stream params
func (o *GetStreamParams) SetIndex(index *string) {
	o.Index = index
}

// WithLink adds the link to the get stream params
func (o *GetStreamParams) WithLink(link string) *GetStreamParams {
	o.SetLink(link)
	return o
}

// SetLink adds the link to the get stream params
func (o *GetStreamParams) SetLink(link string) {
	o.Link = link
}

// WithM3u adds the m3u to the get stream params
func (o *GetStreamParams) WithM3u(m3u *string) *GetStreamParams {
	o.SetM3u(m3u)
	return o
}

// SetM3u adds the m3u to the get stream params
func (o *GetStreamParams) SetM3u(m3u *string) {
	o.M3u = m3u
}

// WithPlay adds the play to the get stream params
func (o *GetStreamParams) WithPlay(play *string) *GetStreamParams {
	o.SetPlay(play)
	return o
}

// SetPlay adds the play to the get stream params
func (o *GetStreamParams) SetPlay(play *string) {
	o.Play = play
}

// WithPoster adds the poster to the get stream params
func (o *GetStreamParams) WithPoster(poster *string) *GetStreamParams {
	o.SetPoster(poster)
	return o
}

// SetPoster adds the poster to the get stream params
func (o *GetStreamParams) SetPoster(poster *string) {
	o.Poster = poster
}

// WithPreload adds the preload to the get stream params
func (o *GetStreamParams) WithPreload(preload *string) *GetStreamParams {
	o.SetPreload(preload)
	return o
}

// SetPreload adds the preload to the get stream params
func (o *GetStreamParams) SetPreload(preload *string) {
	o.Preload = preload
}

// WithSave adds the save to the get stream params
func (o *GetStreamParams) WithSave(save *string) *GetStreamParams {
	o.SetSave(save)
	return o
}

// SetSave adds the save to the get stream params
func (o *GetStreamParams) SetSave(save *string) {
	o.Save = save
}

// WithStat adds the stat to the get stream params
func (o *GetStreamParams) WithStat(stat *string) *GetStreamParams {
	o.SetStat(stat)
	return o
}

// SetStat adds the stat to the get stream params
func (o *GetStreamParams) SetStat(stat *string) {
	o.Stat = stat
}

// WithTitle adds the title to the get stream params
func (o *GetStreamParams) WithTitle(title *string) *GetStreamParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the get stream params
func (o *GetStreamParams) SetTitle(title *string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *GetStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Category != nil {

		// query param category
		var qrCategory string

		if o.Category != nil {
			qrCategory = *o.Category
		}
		qCategory := qrCategory
		if qCategory != "" {

			if err := r.SetQueryParam("category", qCategory); err != nil {
				return err
			}
		}
	}

	if o.Fromlast != nil {

		// query param fromlast
		var qrFromlast string

		if o.Fromlast != nil {
			qrFromlast = *o.Fromlast
		}
		qFromlast := qrFromlast
		if qFromlast != "" {

			if err := r.SetQueryParam("fromlast", qFromlast); err != nil {
				return err
			}
		}
	}

	if o.Index != nil {

		// query param index
		var qrIndex string

		if o.Index != nil {
			qrIndex = *o.Index
		}
		qIndex := qrIndex
		if qIndex != "" {

			if err := r.SetQueryParam("index", qIndex); err != nil {
				return err
			}
		}
	}

	// query param link
	qrLink := o.Link
	qLink := qrLink
	if qLink != "" {

		if err := r.SetQueryParam("link", qLink); err != nil {
			return err
		}
	}

	if o.M3u != nil {

		// query param m3u
		var qrM3u string

		if o.M3u != nil {
			qrM3u = *o.M3u
		}
		qM3u := qrM3u
		if qM3u != "" {

			if err := r.SetQueryParam("m3u", qM3u); err != nil {
				return err
			}
		}
	}

	if o.Play != nil {

		// query param play
		var qrPlay string

		if o.Play != nil {
			qrPlay = *o.Play
		}
		qPlay := qrPlay
		if qPlay != "" {

			if err := r.SetQueryParam("play", qPlay); err != nil {
				return err
			}
		}
	}

	if o.Poster != nil {

		// query param poster
		var qrPoster string

		if o.Poster != nil {
			qrPoster = *o.Poster
		}
		qPoster := qrPoster
		if qPoster != "" {

			if err := r.SetQueryParam("poster", qPoster); err != nil {
				return err
			}
		}
	}

	if o.Preload != nil {

		// query param preload
		var qrPreload string

		if o.Preload != nil {
			qrPreload = *o.Preload
		}
		qPreload := qrPreload
		if qPreload != "" {

			if err := r.SetQueryParam("preload", qPreload); err != nil {
				return err
			}
		}
	}

	if o.Save != nil {

		// query param save
		var qrSave string

		if o.Save != nil {
			qrSave = *o.Save
		}
		qSave := qrSave
		if qSave != "" {

			if err := r.SetQueryParam("save", qSave); err != nil {
				return err
			}
		}
	}

	if o.Stat != nil {

		// query param stat
		var qrStat string

		if o.Stat != nil {
			qrStat = *o.Stat
		}
		qStat := qrStat
		if qStat != "" {

			if err := r.SetQueryParam("stat", qStat); err != nil {
				return err
			}
		}
	}

	if o.Title != nil {

		// query param title
		var qrTitle string

		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {

			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
