// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetShutdownReader is a Reader for the GetShutdown structure.
type GetShutdownReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetShutdownReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetShutdownOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /shutdown] GetShutdown", response, response.Code())
	}
}

// NewGetShutdownOK creates a GetShutdownOK with default headers values
func NewGetShutdownOK() *GetShutdownOK {
	return &GetShutdownOK{}
}

/*
GetShutdownOK describes a response with status code 200, with default header values.

OK
*/
type GetShutdownOK struct {
}

// IsSuccess returns true when this get shutdown o k response has a 2xx status code
func (o *GetShutdownOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get shutdown o k response has a 3xx status code
func (o *GetShutdownOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get shutdown o k response has a 4xx status code
func (o *GetShutdownOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get shutdown o k response has a 5xx status code
func (o *GetShutdownOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get shutdown o k response a status code equal to that given
func (o *GetShutdownOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get shutdown o k response
func (o *GetShutdownOK) Code() int {
	return 200
}

func (o *GetShutdownOK) Error() string {
	return fmt.Sprintf("[GET /shutdown][%d] getShutdownOK", 200)
}

func (o *GetShutdownOK) String() string {
	return fmt.Sprintf("[GET /shutdown][%d] getShutdownOK", 200)
}

func (o *GetShutdownOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
