// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetFfpHashIDReader is a Reader for the GetFfpHashID structure.
type GetFfpHashIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFfpHashIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetFfpHashIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ffp/{hash}/{id}] GetFfpHashID", response, response.Code())
	}
}

// NewGetFfpHashIDOK creates a GetFfpHashIDOK with default headers values
func NewGetFfpHashIDOK() *GetFfpHashIDOK {
	return &GetFfpHashIDOK{}
}

/*
GetFfpHashIDOK describes a response with status code 200, with default header values.

Data returned from ffprobe
*/
type GetFfpHashIDOK struct {
}

// IsSuccess returns true when this get ffp hash Id o k response has a 2xx status code
func (o *GetFfpHashIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ffp hash Id o k response has a 3xx status code
func (o *GetFfpHashIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ffp hash Id o k response has a 4xx status code
func (o *GetFfpHashIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ffp hash Id o k response has a 5xx status code
func (o *GetFfpHashIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ffp hash Id o k response a status code equal to that given
func (o *GetFfpHashIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get ffp hash Id o k response
func (o *GetFfpHashIDOK) Code() int {
	return 200
}

func (o *GetFfpHashIDOK) Error() string {
	return fmt.Sprintf("[GET /ffp/{hash}/{id}][%d] getFfpHashIdOK", 200)
}

func (o *GetFfpHashIDOK) String() string {
	return fmt.Sprintf("[GET /ffp/{hash}/{id}][%d] getFfpHashIdOK", 200)
}

func (o *GetFfpHashIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
