// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEchoParams creates a new GetEchoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEchoParams() *GetEchoParams {
	return &GetEchoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEchoParamsWithTimeout creates a new GetEchoParams object
// with the ability to set a timeout on a request.
func NewGetEchoParamsWithTimeout(timeout time.Duration) *GetEchoParams {
	return &GetEchoParams{
		timeout: timeout,
	}
}

// NewGetEchoParamsWithContext creates a new GetEchoParams object
// with the ability to set a context for a request.
func NewGetEchoParamsWithContext(ctx context.Context) *GetEchoParams {
	return &GetEchoParams{
		Context: ctx,
	}
}

// NewGetEchoParamsWithHTTPClient creates a new GetEchoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEchoParamsWithHTTPClient(client *http.Client) *GetEchoParams {
	return &GetEchoParams{
		HTTPClient: client,
	}
}

/*
GetEchoParams contains all the parameters to send to the API endpoint

	for the get echo operation.

	Typically these are written to a http.Request.
*/
type GetEchoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get echo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEchoParams) WithDefaults() *GetEchoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get echo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEchoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get echo params
func (o *GetEchoParams) WithTimeout(timeout time.Duration) *GetEchoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get echo params
func (o *GetEchoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get echo params
func (o *GetEchoParams) WithContext(ctx context.Context) *GetEchoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get echo params
func (o *GetEchoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get echo params
func (o *GetEchoParams) WithHTTPClient(client *http.Client) *GetEchoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get echo params
func (o *GetEchoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetEchoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
