// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDownloadSizeReader is a Reader for the GetDownloadSize structure.
type GetDownloadSizeReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetDownloadSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetDownloadSizeOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /download/{size}] GetDownloadSize", response, response.Code())
	}
}

// NewGetDownloadSizeOK creates a GetDownloadSizeOK with default headers values
func NewGetDownloadSizeOK(writer io.Writer) *GetDownloadSizeOK {
	return &GetDownloadSizeOK{

		Payload: writer,
	}
}

/*
GetDownloadSizeOK describes a response with status code 200, with default header values.

OK
*/
type GetDownloadSizeOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get download size o k response has a 2xx status code
func (o *GetDownloadSizeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get download size o k response has a 3xx status code
func (o *GetDownloadSizeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get download size o k response has a 4xx status code
func (o *GetDownloadSizeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get download size o k response has a 5xx status code
func (o *GetDownloadSizeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get download size o k response a status code equal to that given
func (o *GetDownloadSizeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get download size o k response
func (o *GetDownloadSizeOK) Code() int {
	return 200
}

func (o *GetDownloadSizeOK) Error() string {
	return fmt.Sprintf("[GET /download/{size}][%d] getDownloadSizeOK", 200)
}

func (o *GetDownloadSizeOK) String() string {
	return fmt.Sprintf("[GET /download/{size}][%d] getDownloadSizeOK", 200)
}

func (o *GetDownloadSizeOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetDownloadSizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
