// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPlaylistReader is a Reader for the GetPlaylist structure.
type GetPlaylistReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetPlaylistReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlaylistOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /playlist] GetPlaylist", response, response.Code())
	}
}

// NewGetPlaylistOK creates a GetPlaylistOK with default headers values
func NewGetPlaylistOK(writer io.Writer) *GetPlaylistOK {
	return &GetPlaylistOK{

		Payload: writer,
	}
}

/*
GetPlaylistOK describes a response with status code 200, with default header values.

OK
*/
type GetPlaylistOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get playlist o k response has a 2xx status code
func (o *GetPlaylistOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get playlist o k response has a 3xx status code
func (o *GetPlaylistOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get playlist o k response has a 4xx status code
func (o *GetPlaylistOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get playlist o k response has a 5xx status code
func (o *GetPlaylistOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get playlist o k response a status code equal to that given
func (o *GetPlaylistOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get playlist o k response
func (o *GetPlaylistOK) Code() int {
	return 200
}

func (o *GetPlaylistOK) Error() string {
	return fmt.Sprintf("[GET /playlist][%d] getPlaylistOK", 200)
}

func (o *GetPlaylistOK) String() string {
	return fmt.Sprintf("[GET /playlist][%d] getPlaylistOK", 200)
}

func (o *GetPlaylistOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetPlaylistOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
