// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPlayHashIDReader is a Reader for the GetPlayHashID structure.
type GetPlayHashIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlayHashIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlayHashIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /play/{hash}/{id}] GetPlayHashID", response, response.Code())
	}
}

// NewGetPlayHashIDOK creates a GetPlayHashIDOK with default headers values
func NewGetPlayHashIDOK() *GetPlayHashIDOK {
	return &GetPlayHashIDOK{}
}

/*
GetPlayHashIDOK describes a response with status code 200, with default header values.

Torrent data
*/
type GetPlayHashIDOK struct {
}

// IsSuccess returns true when this get play hash Id o k response has a 2xx status code
func (o *GetPlayHashIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get play hash Id o k response has a 3xx status code
func (o *GetPlayHashIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get play hash Id o k response has a 4xx status code
func (o *GetPlayHashIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get play hash Id o k response has a 5xx status code
func (o *GetPlayHashIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get play hash Id o k response a status code equal to that given
func (o *GetPlayHashIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get play hash Id o k response
func (o *GetPlayHashIDOK) Code() int {
	return 200
}

func (o *GetPlayHashIDOK) Error() string {
	return fmt.Sprintf("[GET /play/{hash}/{id}][%d] getPlayHashIdOK", 200)
}

func (o *GetPlayHashIDOK) String() string {
	return fmt.Sprintf("[GET /play/{hash}/{id}][%d] getPlayHashIdOK", 200)
}

func (o *GetPlayHashIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
