// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/pkg/torrserver/models"
)

// GetSearchReader is a Reader for the GetSearch structure.
type GetSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /search] GetSearch", response, response.Code())
	}
}

// NewGetSearchOK creates a GetSearchOK with default headers values
func NewGetSearchOK() *GetSearchOK {
	return &GetSearchOK{}
}

/*
GetSearchOK describes a response with status code 200, with default header values.

Rutor torrent search result(s)
*/
type GetSearchOK struct {
	Payload []*models.ModelsTorrentDetails
}

// IsSuccess returns true when this get search o k response has a 2xx status code
func (o *GetSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get search o k response has a 3xx status code
func (o *GetSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get search o k response has a 4xx status code
func (o *GetSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get search o k response has a 5xx status code
func (o *GetSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get search o k response a status code equal to that given
func (o *GetSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get search o k response
func (o *GetSearchOK) Code() int {
	return 200
}

func (o *GetSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /search][%d] getSearchOK %s", 200, payload)
}

func (o *GetSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /search][%d] getSearchOK %s", 200, payload)
}

func (o *GetSearchOK) GetPayload() []*models.ModelsTorrentDetails {
	return o.Payload
}

func (o *GetSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
