// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/v4/pkg/torrserver/models"
)

// PostTorrentUploadReader is a Reader for the PostTorrentUpload structure.
type PostTorrentUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTorrentUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostTorrentUploadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /torrent/upload] PostTorrentUpload", response, response.Code())
	}
}

// NewPostTorrentUploadOK creates a PostTorrentUploadOK with default headers values
func NewPostTorrentUploadOK() *PostTorrentUploadOK {
	return &PostTorrentUploadOK{}
}

/*
PostTorrentUploadOK describes a response with status code 200, with default header values.

Torrent status
*/
type PostTorrentUploadOK struct {
	Payload *models.StateTorrentStatus
}

// IsSuccess returns true when this post torrent upload o k response has a 2xx status code
func (o *PostTorrentUploadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post torrent upload o k response has a 3xx status code
func (o *PostTorrentUploadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post torrent upload o k response has a 4xx status code
func (o *PostTorrentUploadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post torrent upload o k response has a 5xx status code
func (o *PostTorrentUploadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post torrent upload o k response a status code equal to that given
func (o *PostTorrentUploadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post torrent upload o k response
func (o *PostTorrentUploadOK) Code() int {
	return 200
}

func (o *PostTorrentUploadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /torrent/upload][%d] postTorrentUploadOK %s", 200, payload)
}

func (o *PostTorrentUploadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /torrent/upload][%d] postTorrentUploadOK %s", 200, payload)
}

func (o *PostTorrentUploadOK) GetPayload() *models.StateTorrentStatus {
	return o.Payload
}

func (o *PostTorrentUploadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StateTorrentStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
