// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/v4/pkg/torrserver/models"
)

// NewPostTorrentsParams creates a new PostTorrentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTorrentsParams() *PostTorrentsParams {
	return &PostTorrentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTorrentsParamsWithTimeout creates a new PostTorrentsParams object
// with the ability to set a timeout on a request.
func NewPostTorrentsParamsWithTimeout(timeout time.Duration) *PostTorrentsParams {
	return &PostTorrentsParams{
		timeout: timeout,
	}
}

// NewPostTorrentsParamsWithContext creates a new PostTorrentsParams object
// with the ability to set a context for a request.
func NewPostTorrentsParamsWithContext(ctx context.Context) *PostTorrentsParams {
	return &PostTorrentsParams{
		Context: ctx,
	}
}

// NewPostTorrentsParamsWithHTTPClient creates a new PostTorrentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTorrentsParamsWithHTTPClient(client *http.Client) *PostTorrentsParams {
	return &PostTorrentsParams{
		HTTPClient: client,
	}
}

/*
PostTorrentsParams contains all the parameters to send to the API endpoint

	for the post torrents operation.

	Typically these are written to a http.Request.
*/
type PostTorrentsParams struct {

	/* Request.

	   Torrent request. Available params for action: add, get, set, rem, list, drop, wipe. link required for add, hash required for get, set, rem, drop.
	*/
	Request *models.APITorrReqJS

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentsParams) WithDefaults() *PostTorrentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post torrents params
func (o *PostTorrentsParams) WithTimeout(timeout time.Duration) *PostTorrentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post torrents params
func (o *PostTorrentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post torrents params
func (o *PostTorrentsParams) WithContext(ctx context.Context) *PostTorrentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post torrents params
func (o *PostTorrentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post torrents params
func (o *PostTorrentsParams) WithHTTPClient(client *http.Client) *PostTorrentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post torrents params
func (o *PostTorrentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post torrents params
func (o *PostTorrentsParams) WithRequest(request *models.APITorrReqJS) *PostTorrentsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post torrents params
func (o *PostTorrentsParams) SetRequest(request *models.APITorrReqJS) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostTorrentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
