// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/pkg/torrserver/models"
)

// PostViewedReader is a Reader for the PostViewed structure.
type PostViewedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostViewedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostViewedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /viewed] PostViewed", response, response.Code())
	}
}

// NewPostViewedOK creates a PostViewedOK with default headers values
func NewPostViewedOK() *PostViewedOK {
	return &PostViewedOK{}
}

/*
PostViewedOK describes a response with status code 200, with default header values.

OK
*/
type PostViewedOK struct {
	Payload []*models.SettingsViewed
}

// IsSuccess returns true when this post viewed o k response has a 2xx status code
func (o *PostViewedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post viewed o k response has a 3xx status code
func (o *PostViewedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post viewed o k response has a 4xx status code
func (o *PostViewedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post viewed o k response has a 5xx status code
func (o *PostViewedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post viewed o k response a status code equal to that given
func (o *PostViewedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post viewed o k response
func (o *PostViewedOK) Code() int {
	return 200
}

func (o *PostViewedOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /viewed][%d] postViewedOK %s", 200, payload)
}

func (o *PostViewedOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /viewed][%d] postViewedOK %s", 200, payload)
}

func (o *PostViewedOK) GetPayload() []*models.SettingsViewed {
	return o.Payload
}

func (o *PostViewedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
