// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/v4/pkg/torrserver/models"
)

// NewPostSettingsParams creates a new PostSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSettingsParams() *PostSettingsParams {
	return &PostSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSettingsParamsWithTimeout creates a new PostSettingsParams object
// with the ability to set a timeout on a request.
func NewPostSettingsParamsWithTimeout(timeout time.Duration) *PostSettingsParams {
	return &PostSettingsParams{
		timeout: timeout,
	}
}

// NewPostSettingsParamsWithContext creates a new PostSettingsParams object
// with the ability to set a context for a request.
func NewPostSettingsParamsWithContext(ctx context.Context) *PostSettingsParams {
	return &PostSettingsParams{
		Context: ctx,
	}
}

// NewPostSettingsParamsWithHTTPClient creates a new PostSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSettingsParamsWithHTTPClient(client *http.Client) *PostSettingsParams {
	return &PostSettingsParams{
		HTTPClient: client,
	}
}

/*
PostSettingsParams contains all the parameters to send to the API endpoint

	for the post settings operation.

	Typically these are written to a http.Request.
*/
type PostSettingsParams struct {

	/* Request.

	   Settings request. Available params for action: get, set, def
	*/
	Request *models.APISetsReqJS

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSettingsParams) WithDefaults() *PostSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post settings params
func (o *PostSettingsParams) WithTimeout(timeout time.Duration) *PostSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post settings params
func (o *PostSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post settings params
func (o *PostSettingsParams) WithContext(ctx context.Context) *PostSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post settings params
func (o *PostSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post settings params
func (o *PostSettingsParams) WithHTTPClient(client *http.Client) *PostSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post settings params
func (o *PostSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post settings params
func (o *PostSettingsParams) WithRequest(request *models.APISetsReqJS) *PostSettingsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post settings params
func (o *PostSettingsParams) SetRequest(request *models.APISetsReqJS) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
