// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostTorrentUploadParams creates a new PostTorrentUploadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTorrentUploadParams() *PostTorrentUploadParams {
	return &PostTorrentUploadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTorrentUploadParamsWithTimeout creates a new PostTorrentUploadParams object
// with the ability to set a timeout on a request.
func NewPostTorrentUploadParamsWithTimeout(timeout time.Duration) *PostTorrentUploadParams {
	return &PostTorrentUploadParams{
		timeout: timeout,
	}
}

// NewPostTorrentUploadParamsWithContext creates a new PostTorrentUploadParams object
// with the ability to set a context for a request.
func NewPostTorrentUploadParamsWithContext(ctx context.Context) *PostTorrentUploadParams {
	return &PostTorrentUploadParams{
		Context: ctx,
	}
}

// NewPostTorrentUploadParamsWithHTTPClient creates a new PostTorrentUploadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTorrentUploadParamsWithHTTPClient(client *http.Client) *PostTorrentUploadParams {
	return &PostTorrentUploadParams{
		HTTPClient: client,
	}
}

/*
PostTorrentUploadParams contains all the parameters to send to the API endpoint

	for the post torrent upload operation.

	Typically these are written to a http.Request.
*/
type PostTorrentUploadParams struct {

	/* Category.

	   Torrent category
	*/
	Category *string

	/* Data.

	   Torrent data
	*/
	Data *string

	/* File.

	   Torrent file to insert
	*/
	File runtime.NamedReadCloser

	/* Poster.

	   Torrent poster
	*/
	Poster *string

	/* Save.

	   Save to DB
	*/
	Save *string

	/* Title.

	   Torrent title
	*/
	Title *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post torrent upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentUploadParams) WithDefaults() *PostTorrentUploadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post torrent upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentUploadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post torrent upload params
func (o *PostTorrentUploadParams) WithTimeout(timeout time.Duration) *PostTorrentUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post torrent upload params
func (o *PostTorrentUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post torrent upload params
func (o *PostTorrentUploadParams) WithContext(ctx context.Context) *PostTorrentUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post torrent upload params
func (o *PostTorrentUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post torrent upload params
func (o *PostTorrentUploadParams) WithHTTPClient(client *http.Client) *PostTorrentUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post torrent upload params
func (o *PostTorrentUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the post torrent upload params
func (o *PostTorrentUploadParams) WithCategory(category *string) *PostTorrentUploadParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the post torrent upload params
func (o *PostTorrentUploadParams) SetCategory(category *string) {
	o.Category = category
}

// WithData adds the data to the post torrent upload params
func (o *PostTorrentUploadParams) WithData(data *string) *PostTorrentUploadParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post torrent upload params
func (o *PostTorrentUploadParams) SetData(data *string) {
	o.Data = data
}

// WithFile adds the file to the post torrent upload params
func (o *PostTorrentUploadParams) WithFile(file runtime.NamedReadCloser) *PostTorrentUploadParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post torrent upload params
func (o *PostTorrentUploadParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithPoster adds the poster to the post torrent upload params
func (o *PostTorrentUploadParams) WithPoster(poster *string) *PostTorrentUploadParams {
	o.SetPoster(poster)
	return o
}

// SetPoster adds the poster to the post torrent upload params
func (o *PostTorrentUploadParams) SetPoster(poster *string) {
	o.Poster = poster
}

// WithSave adds the save to the post torrent upload params
func (o *PostTorrentUploadParams) WithSave(save *string) *PostTorrentUploadParams {
	o.SetSave(save)
	return o
}

// SetSave adds the save to the post torrent upload params
func (o *PostTorrentUploadParams) SetSave(save *string) {
	o.Save = save
}

// WithTitle adds the title to the post torrent upload params
func (o *PostTorrentUploadParams) WithTitle(title *string) *PostTorrentUploadParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the post torrent upload params
func (o *PostTorrentUploadParams) SetTitle(title *string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *PostTorrentUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Category != nil {

		// form param category
		var frCategory string
		if o.Category != nil {
			frCategory = *o.Category
		}
		fCategory := frCategory
		if fCategory != "" {
			if err := r.SetFormParam("category", fCategory); err != nil {
				return err
			}
		}
	}

	if o.Data != nil {

		// form param data
		var frData string
		if o.Data != nil {
			frData = *o.Data
		}
		fData := frData
		if fData != "" {
			if err := r.SetFormParam("data", fData); err != nil {
				return err
			}
		}
	}
	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	if o.Poster != nil {

		// form param poster
		var frPoster string
		if o.Poster != nil {
			frPoster = *o.Poster
		}
		fPoster := frPoster
		if fPoster != "" {
			if err := r.SetFormParam("poster", fPoster); err != nil {
				return err
			}
		}
	}

	if o.Save != nil {

		// form param save
		var frSave string
		if o.Save != nil {
			frSave = *o.Save
		}
		fSave := frSave
		if fSave != "" {
			if err := r.SetFormParam("save", fSave); err != nil {
				return err
			}
		}
	}

	if o.Title != nil {

		// form param title
		var frTitle string
		if o.Title != nil {
			frTitle = *o.Title
		}
		fTitle := frTitle
		if fTitle != "" {
			if err := r.SetFormParam("title", fTitle); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
