// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-torrent/pkg/torrserver/models"
)

// NewPostViewedParams creates a new PostViewedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostViewedParams() *PostViewedParams {
	return &PostViewedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostViewedParamsWithTimeout creates a new PostViewedParams object
// with the ability to set a timeout on a request.
func NewPostViewedParamsWithTimeout(timeout time.Duration) *PostViewedParams {
	return &PostViewedParams{
		timeout: timeout,
	}
}

// NewPostViewedParamsWithContext creates a new PostViewedParams object
// with the ability to set a context for a request.
func NewPostViewedParamsWithContext(ctx context.Context) *PostViewedParams {
	return &PostViewedParams{
		Context: ctx,
	}
}

// NewPostViewedParamsWithHTTPClient creates a new PostViewedParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostViewedParamsWithHTTPClient(client *http.Client) *PostViewedParams {
	return &PostViewedParams{
		HTTPClient: client,
	}
}

/*
PostViewedParams contains all the parameters to send to the API endpoint

	for the post viewed operation.

	Typically these are written to a http.Request.
*/
type PostViewedParams struct {

	/* Request.

	   Viewed torrent request. Available params for action: set, rem, list
	*/
	Request *models.APIViewedReqJS

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post viewed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostViewedParams) WithDefaults() *PostViewedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post viewed params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostViewedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post viewed params
func (o *PostViewedParams) WithTimeout(timeout time.Duration) *PostViewedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post viewed params
func (o *PostViewedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post viewed params
func (o *PostViewedParams) WithContext(ctx context.Context) *PostViewedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post viewed params
func (o *PostViewedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post viewed params
func (o *PostViewedParams) WithHTTPClient(client *http.Client) *PostViewedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post viewed params
func (o *PostViewedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post viewed params
func (o *PostViewedParams) WithRequest(request *models.APIViewedReqJS) *PostViewedParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post viewed params
func (o *PostViewedParams) SetRequest(request *models.APIViewedReqJS) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostViewedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
