// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostTorrentsReader is a Reader for the PostTorrents structure.
type PostTorrentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTorrentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostTorrentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /torrents] PostTorrents", response, response.Code())
	}
}

// NewPostTorrentsOK creates a PostTorrentsOK with default headers values
func NewPostTorrentsOK() *PostTorrentsOK {
	return &PostTorrentsOK{}
}

/*
PostTorrentsOK describes a response with status code 200, with default header values.

OK
*/
type PostTorrentsOK struct {
}

// IsSuccess returns true when this post torrents o k response has a 2xx status code
func (o *PostTorrentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post torrents o k response has a 3xx status code
func (o *PostTorrentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post torrents o k response has a 4xx status code
func (o *PostTorrentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post torrents o k response has a 5xx status code
func (o *PostTorrentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post torrents o k response a status code equal to that given
func (o *PostTorrentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post torrents o k response
func (o *PostTorrentsOK) Code() int {
	return 200
}

func (o *PostTorrentsOK) Error() string {
	return fmt.Sprintf("[POST /torrents][%d] postTorrentsOK", 200)
}

func (o *PostTorrentsOK) String() string {
	return fmt.Sprintf("[POST /torrents][%d] postTorrentsOK", 200)
}

func (o *PostTorrentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
