name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: racoonmediaserver/torrent
          registry: docker.io
          tags: ${{ github.ref_name }}, latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}